# DO NOT EDIT THIS FILE!
#
# Python module AAS_CORBA__POA generated by omniidl

import omniORB
omniORB.updateModule("AAS_CORBA__POA")

# ** 1. Stub files contributing to this module
import CoFluentUnit_idl

# ** 2. Sub-modules

# ** 3. End
